const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';
const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';

const FIRST_BACKGROUND_MOVIE_SUCCESS = 'FIRST_BACKGROUND_MOVIE_SUCCESS';
const FIRST_BACKGROUND_MOVIE_FAILURE = 'FIRST_BACKGROUND_MOVIE_FAILURE';

const LOADING_SUCCESS = 'LOADING_SUCCESS';
const LOADING_FAILURE = 'LOADING_FAILURE';

const LOAD_BG_HEADER_SUCCESS = 'LOAD_BG_HEADER_SUCCESS';
const LOAD_BG_HEADER_FAILURE = 'LOAD_BG_HEADER_FAILURE';

const INDEX_ALL_CATALOG_SUCCESS = 'INDEX_ALL_CATALOG_SUCCESS';
const INDEX_ALL_CATALOG_FAILURE = 'INDEX_ALL_CATALOG_FAILURE';

const LOAD_USER_PHOTO_SUCCESS = 'LOAD_USER_PHOTO_SUCCESS';
const LOAD_USER_PHOTO_FAILURE = 'LOAD_BG_HEADER_FAILURE';

export {
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILURE,
  USER_LOGIN_REQUEST,
  FIRST_BACKGROUND_MOVIE_SUCCESS,
  FIRST_BACKGROUND_MOVIE_FAILURE,
  LOADING_SUCCESS,
  LOADING_FAILURE,
  LOAD_BG_HEADER_SUCCESS,
  LOAD_BG_HEADER_FAILURE,
  INDEX_ALL_CATALOG_SUCCESS,
  INDEX_ALL_CATALOG_FAILURE,
  LOAD_USER_PHOTO_SUCCESS,
  LOAD_USER_PHOTO_FAILURE,
};
