const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

const USER_NEW_DATA_SUCCESS = 'USER_NEW_DATA_SUCCESS';

const FIRST_BACKGROUND_SUCCESS = 'FIRST_BACKGROUND_SUCCESS';
const FIRST_BACKGROUND_FAILURE = 'FIRST_BACKGROUND_FAILURE';

const LOADING_SUCCESS = 'LOADING_SUCCESS';
const LOADING_FAILURE = 'LOADING_FAILURE';

const LOAD_BG_HEADER_SUCCESS = 'LOAD_BG_HEADER_SUCCESS';
const LOAD_BG_HEADER_FAILURE = 'LOAD_BG_HEADER_FAILURE';

const INDEX_ALL_CATALOG_SUCCESS = 'INDEX_ALL_CATALOG_SUCCESS';
const INDEX_ALL_CATALOG_FAILURE = 'INDEX_ALL_CATALOG_FAILURE';

export {
  USER_LOGIN_SUCCESS,
  USER_LOGIN_FAILURE,
  USER_NEW_DATA_SUCCESS,
  FIRST_BACKGROUND_SUCCESS,
  FIRST_BACKGROUND_FAILURE,
  LOADING_SUCCESS,
  LOADING_FAILURE,
  LOAD_BG_HEADER_SUCCESS,
  LOAD_BG_HEADER_FAILURE,
  INDEX_ALL_CATALOG_SUCCESS,
  INDEX_ALL_CATALOG_FAILURE,
};
